const CardData = [
  {
    id: 1,
    image: "https://vifloor2006.com/wp-content/uploads/2023/03/burma-teak-engineered-floor1-600x370.jpg",
    title: "Premium Burma Teak",
    category: "Hardwood",
    description: "Highly durable, weather-resistant wood with rich golden grains. Ideal for premium outdoor decking and luxury furniture.",
    price: "₹3,200/cft",
  },
  {
    id: 2,
    image: "https://m.media-amazon.com/images/I/81RfsQq9+DL.jpg",
    title: "American White Oak",
    category: "Hardwood",
    description: "Exceptionally strong and water-resistant wood with prominent growth rings. Preferred for cabinetry and flooring.",
    price: "₹2,800/cft",
  },
  {
    id: 3,
    image: "https://plazaboard.co.za/wp-content/uploads/2020/01/Novolam-Royal-Mahogany.jpg",
    title: "Royal Mahogany",
    category: "Exotic Hardwood",
    description: "A dense, rich reddish-brown wood that resists wood rot and shrinkage. Ideal for high-end carpentry and instruments.",
    price: "₹4,500/cft",
  },
  {
    id: 4,
    image: "https://www.timbersource.co.uk/application/files/7917/3141/1112/Yellow_Pine_400x400.png",
    title: "Premium Yellow Pine",
    category: "Softwood",
    description: "Lightweight and easy to work with softwood. Excellent for general structural framing, cladding, and rustic interior projects.",
    price: "₹1,200/cft",
  },
  {
    id: 5,
    image: "https://i.pinimg.com/originals/28/c0/0a/28c00ad1a2f3ab98cf0901bf59453962.jpg",
    title: "American Black Walnut",
    category: "Premium Hardwood",
    description: "Dark, rich chocolate-brown wood with elegant swirling grain patterns. Highly prized for luxury executive desks and cabinetry.",
    price: "₹5,200/cft",
  },
  {
    id: 6,
    image: "https://jbcutting.com/wp-content/uploads/2021/09/Hard-Rock-Maple.jpg",
    title: "Hard Rock Maple",
    category: "Hardwood",
    description: "Extremely hard, heavy, and abrasion-resistant wood with a light cream color. Perfect for cutting boards and heavy-duty flooring.",
    price: "₹3,100/cft",
  },
  {
    id: 7,
    image: "https://tse2.mm.bing.net/th/id/OIP.7lvXmfZweOEoIDWw-xxrlgHaG9?r=0&pid=Api&P=0&h=180",
    title: "American Black Cherry",
    category: "Hardwood",
    description: "Highly esteemed wood with rich red-warm tones that darken beautifully with sunlight exposure. Silky smooth texture, excellent for fine cabinetry.",
    price: "₹3,400/cft",
  },
  {
    id: 8,
    image: "https://www.wood-database.com/wp-content/uploads/douglas-fir-sealed.jpg",
    title: "Coastal Douglas Fir",
    category: "Softwood",
    description: "One of the strongest and most stable softwoods. Distinct light brown color with a hint of red, widely used for heavy structural beams.",
    price: "₹1,450/cft",
  },
  {
    id: 9,
    image: "https://www.wood-database.com/wp-content/uploads/east-indian-rosewood-sealed.jpg",
    title: "East Indian Rosewood",
    category: "Exotic Hardwood",
    description: "Dense exotic wood displaying beautiful dark purple-brown stripes. Famous for premium acoustic guitars and luxury carvings.",
    price: "₹5,800/cft",
  },
];

export default CardData;